name: '[docker] CI for releases'

on:
    push:
        branches: master

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            uses: actions/checkout@v1
        -
            name: Login to DockerHub Registry
            env:
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
                run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        -
            name: Set up Docker Buildx
            id: buildx
            uses: crazy-max/ghaction-docker-buildx@v1
            with:
                version: latest
        -
            name: Build dockerfile (with push)
            env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
                docker buildx build \
                --platform linux/amd64,linux/arm64 \
                --output "type=image,push=true" \
                --file ./Dockerfile . \
                --tag $(echo "${DOCKER_USERNAME}" | tr '[:upper:]' '[:lower:]')/webw:latest
